# Use the official Node.js image as a base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

COPY muddy-app/* ./
# Install project dependencies
RUN npm install


# Expose the port that Expo will run on (default is 19000)
EXPOSE 19000
EXPOSE 19001

# Start the Expo development server when the container starts
CMD ["npx", "expo", "start"]
