# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Environment variables to configure PostgreSQL
ENV POSTGRES_DB=assessment_db
ENV POSTGRES_USER=AB_user
ENV POSTGRES_PASSWORD=pass

VOLUME /var/lib/postgresql/data

# Expose the default PostgreSQL port
EXPOSE 5432
#Run to reset wipe data
COPY seed_db.sql /docker-entrypoint-initdb.d/
# Create a directory for the PostgreSQL data volume
RUN mkdir -p /var/lib/postgresql/data

# Start the PostgreSQL server
CMD ["postgres"]
