FROM python:3.10

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port used by the Django development server
EXPOSE 8000

# Run the development server with SSL
CMD ["python", "manage.py", "runserver_plus", "--cert-file", ".secret/cert.pem", "--key-file", ".secret/key.pem"]
