# Dockerfile.nginx
FROM nginx:latest

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificate and key
COPY .secret/certificate.crt /etc/nginx/.secret/certificate.crt
COPY .secret/private.key /etc/nginx/.secret/private.key

# Set passphrase for SSL key
#No passphrase
# Nginx setup...
